# initially copied from https://github.com/harshjv/travis-ci-latex-pdf/blob/master/.travis.yml
sudo: required
#dist: trusty
dist: xenial
before_install:
# on a merge commit, we are going to push to ximera.
- if [[ "$TRAVIS_PULL_REQUEST" == "false" ]] ; then git checkout master ; fi
- git remote add ximera "https://xake:${token}@ximera.osu.edu/la.git"
- sudo apt-get -qq update && sudo apt-get install -y --no-install-recommends texlive-full texlive-fonts-recommended texlive-latex-extra texlive-fonts-extra dvipng texlive-latex-recommended texlive-pictures libgit2* 
- wget https://github.com/XimeraProject/xake/releases/download/v0.9.4/xake_0.9.4_amd64.deb
- sudo dpkg -i xake_0.9.4_amd64.deb
- mkdir -p ~/texmf/tex/latex
- (cd ~/texmf/tex/latex ; git clone https://github.com/XimeraProject/ximeraLatex.git )
before_script:
- xake clean
- xake name la
script:
- xake bake
- xake frost
after_success:
- if [[ "$TRAVIS_PULL_REQUEST" == "false" ]] ; then git push -c "http.https://ximera.osu.edu/.extraheader=Authorization: Bearer ${token}" ximera; xake serve ; fi
